### ISSUE TITLE
Training duration

### ISSUE THREAD

**Issue by matejgrcic** [thu-ml/vflow#1]
Hi!

You've said, "All the experiments are run on 16 RTX 2080Ti GPUs." in the corresponding paper.
Could you be more specific and provide the per dataset training duration?

Kind regards,
Matej

**Comment by LuChengTHU** [comment]
Hi @matejgrcic , thanks for the question. We trained our CIFAR-10 model on 16 RTX 2080Ti GPUs for about 3 weeks, and our ImageNet32x32, ImageNet64x64 models on 16 Tesla V100 GPUs for nearly 2 months, because the models are too big.

Our ImageNet experiments were done after our submission, and we forgot to change this statement of GPU. Thanks for pointing it out!

**Comment by matejgrcic** [comment]
Thank you for the reply!
